### ISSUE TITLE
There is no extract_meta_cv in the isplutils.utils

### ISSUE THREAD

**Issue by zhangconghhh** [polimi-ispl/icpr2020dfdc#1]
When I run the index_ffpp.py, it came out with the error, there is no defination about extract_meta_cv. I found no function about extract_meta_cv  in isplutils.utils.

**Comment by CrohnEngineer** [comment]
Hi @zhangconghhh ,

the function got lost while we were uploading the first release of the repository :)
Now we have added it, so _index_ffpp.py_ should run (hopefully) with no problems. 
Let us know if you encounter other issues, and thank you for checking out our project :)
Cheers!

Edoardo
