### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'videos'

### ISSUE THREAD

**Issue by 2151330** [polimi-ispl/icpr2020dfdc#10]
When I run index_dfdc.py, I get this error, can anyone help me?
![image](https://user-images.githubusercontent.com/41284417/97840289-b6523f80-1d1e-11eb-9f32-1bb0321bab78.png)

**Comment by nicobonne** [comment]
Hi @2151330, 
it seems to me there is a problem in splitting the json path. Somehow, you get the word "videos" instead of the folder number. 
Did you change something in the folder structure of the DFDC? Are you sure you provided the right path to the script?

**Comment by 2151330** [comment]
I get it, thank you
