### ISSUE TITLE
about extract_faces.py

### ISSUE THREAD

**Issue by 2151330** [polimi-ispl/icpr2020dfdc#11]
I did not change the structure of the DFDC dataset, but when I run extract_faces.py, I get the following error. Can you help me solve it?

Error while reading: /data0/DFDC/tmp/dfdc_train_part_9/zzivhztyyn.faces.pkl
rename() got an unexpected keyword argument "errors"
Error while reading: /data0/DFDC/tmp/dfdc_train_part_9/zzkzxqgbcy.faces.pkl
rename() got an unexpected keyword argument "errors"
Collecting faces results: 100%|???????????????????????????????????| 119154/119154 [02:40<00:00, 740.14it/s]
Saving videos DataFrame to /home/**/dfdc/data/dfdc_videos.pkl
Saving faces DataFrame to /data0/DFDC/faces/df_from_video_0_to_video_0.pkl
Traceback (most recent call last):
  File "extract_faces.py", line 306, in <module>
    main()
  File "extract_faces.py", line 157, in main
    df_faces = pd.concat(faces_dataset, axis=0, )
  File "/home/**/anaconda3/envs/icpr2020/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/home/**/anaconda3/envs/icpr2020/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by nicobonne** [comment]
I see you modified the code. Provided that there are no errors in the three lines you added, try to debug and stop to the line `if video_face_checkpoint_path.exists():`. You fail to enter that `if` due to a missing `pkl`. Try to investigate while that file do not exist.
