### ISSUE TITLE
Training with partial dataset

### ISSUE THREAD

**Issue by zhuzhen1996** [polimi-ispl/icpr2020dfdc#27]
Hello, I have processed the face programs of the dfdc dataset and the Celeb dataset according to your instructions. But I have some doubts about the data set segmentation in your code. Is it to run the split.py program? The name of the available dataset is different from the one I downloaded. Because the dfdc data set is too big, I only downloaded part of it. May I ask how to modify this program in split.py.
![image](https://user-images.githubusercontent.com/55490753/113119727-587d4180-9243-11eb-8c5e-3eb38ee31040.png)

The following is the dfdc data set I downloaded
![image](https://user-images.githubusercontent.com/55490753/113119838-79459700-9243-11eb-917c-f700dbc27d29.png)

**Comment by zhuzhen1996** [comment]
Okay, thank you! I try to download all the data sets. If I use the celeb data set for training, I need to artificially divide the three folders under the data set for training, testing, and verification, right? Thank you for your suggestion.

**Comment by nicobonne** [comment]
Yes, you can also use the `celebdf` split we added with commit 6d79abc. Keep in mind that we do not used the CelebDF in the paper, the split is there just for convenience.

**Comment by zhuzhen1996** [comment]
Thank you very much for your help!
