### ISSUE TITLE
Incomplete faces extraction

### ISSUE THREAD

**Issue by zhuzhen1996** [polimi-ispl/icpr2020dfdc#33]
Sorry to trouble you again! The DFDC data set is too big to download at one time. I divided it into 50 downloads. It hasn't finished downloading yet, it's about forty. When I ran extract_faces.py, I found that only the dfdc_train_part_0 folder was processed, and the remaining 30 or more folders were not processed. Does the complete data set and the separated data set have more txt files like celeb? And you can add celeb's data set training in train_all.sh. Thank you very much!
![image](https://user-images.githubusercontent.com/55490753/113823235-fe373000-97b0-11eb-9da5-ef05f0fcf268.png)

**Comment by nicobonne** [comment]
Could you tell us which parameters you used for indexing the incomplete DFDC and for extracting the faces? It's hard to tell without furhter details. 

Regarding CelebDF, we won't insert it in `train_all.sh`, as it is not a dataset used in the paper. You can still figure out how to proceed with training, starting with the parameters for the other datasets.

**Comment by zhuzhen1996** [comment]
您好，我使用了命令：python extract_faces.py --source F:\dataset\dfdc\DFDC --videodf ./data/dfdc_videos.pkl --facesfolder F:\dataset\dfdc\faces --facesdf F:\dataset\dfdc\facedataframe --checkpoint F:\dataset\dfdc\checkpoint
Below is the structure of my DFDC data set folder
![image](https://user-images.githubusercontent.com/55490753/113829745-6e957f80-97b8-11eb-8856-61c39608b2bb.png)
![image](https://user-images.githubusercontent.com/55490753/113829760-73f2ca00-97b8-11eb-8d63-f201d0ad56b9.png)
The following is the organization of the IDE project, the pkl file I get when I run the index_dfdc.py file
![image](https://user-images.githubusercontent.com/55490753/113829950-adc3d080-97b8-11eb-92af-a2c4bcd43cd0.png)

**Comment by zhuzhen1996** [comment]
I downloaded six or seven segmentation data sets before, and when I ran the above program, only the first two came out. And the second one is not complete yet
![image](https://user-images.githubusercontent.com/55490753/113830457-380c3480-97b9-11eb-9ab6-e32712bc51b4.png)
![image](https://user-images.githubusercontent.com/55490753/113830476-3c385200-97b9-11eb-9be3-88e902ffa14c.png)
![image](https://user-images.githubusercontent.com/55490753/113830494-41959c80-97b9-11eb-985c-b22490366235.png)

**Comment by nicobonne** [comment]
Did you run the indexing script when you only had the `dfdc_train_part_0` and `dfdc_train_part_1` folders?

**Comment by zhuzhen1996** [comment]
NO，Before running the index script, and I use the python program to view the corresponding pkl file. There is no problem with checking the number of videos. My biggest doubt now is whether the structure of the DFDC complete data set is the same as the data set I downloaded separately

**Comment by nicobonne** [comment]
So, can you confirm that if you debug `extract_faces.py` and stop on [line 81](https://github.com/polimi-ispl/icpr2020dfdc/blob/f7039ecf3b62369db97b11dc7071e1091e042aa2/extract_faces.py#L81), if you evaluate
```python
df_videos.folder.unique()
````
you get something like this:
```python
Out[2]: 
array([ 0,  1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29,  3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        4, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  5,  6,  7,  8,  9],
      dtype=uint8)
```
with numbers other than 0 and 1?

**Comment by zhuzhen1996** [comment]
You can get the following output
![image](https://user-images.githubusercontent.com/55490753/113842453-419b9980-97c5-11eb-9ab8-54fd4c85a005.png)

**Comment by nicobonne** [comment]
Later today we will merge a Pull Request which should have some more checks to catch silent errors which could have occurred in your case. 

Meanwhile, could you please tell us the output of:
```python
print(df_videos.folder.value_counts())
```

In the case of the complete DFDC indexing you should have:
```python
13    3694
6     3464
10    3192
49    3134
24    2786
19    2752
18    2686
44    2665
34    2658
37    2655
29    2557
39    2556
43    2546
25    2546
35    2540
5     2483
38    2477
7     2473
31    2470
14    2464
48    2463
26    2433
17    2430
40    2420
23    2410
22    2409
47    2406
42    2384
32    2356
27    2353
45    2346
36    2339
33    2274
15    2273
21    2268
30    2236
12    2225
41    2222
46    2202
20    2154
11    2118
28    2085
16    2061
8     1816
2     1748
9     1736
4     1701
1     1699
3     1455
0     1334
Name: folder, dtype: int64
```

**Comment by zhuzhen1996** [comment]
Can get：
![image](https://user-images.githubusercontent.com/55490753/113849558-3861fb00-97cc-11eb-862d-291d1b89bfa0.png)
![image](https://user-images.githubusercontent.com/55490753/113849577-3bf58200-97cc-11eb-8ce8-251af3ddfe5f.png)

**Comment by nicobonne** [comment]
Ok, and the faces extraction with the parameters you specified above runs without errors but you get only the faces from the first two folders, correct?

**Comment by zhuzhen1996** [comment]
Yes, except for the first five write parameters that need to be passed. No need to pass the reference if there is no required later, right? Just use the default parameters. --offset and --num need to modify the parameters

**Comment by nicobonne** [comment]
Yes, the code should run with just the required parameters (the first 5).

**Comment by zhuzhen1996** [comment]
Okay, thank you for your help. I try to run it again

**Comment by nicobonne** [comment]
I'm running some checks. Could you please provide me the output of:
```python
df_videos[df_videos.frames > 0].groupby('folder').apply(lambda x: len(x))
```

**Comment by zhuzhen1996** [comment]
I ran it and got the following output:
![image](https://user-images.githubusercontent.com/55490753/113872455-7bc96300-97e6-11eb-8114-14e193ff0fa5.png)
![image](https://user-images.githubusercontent.com/55490753/113872469-7ff58080-97e6-11eb-8358-cbc60019ce77.png)
![image](https://user-images.githubusercontent.com/55490753/113872486-83890780-97e6-11eb-9828-a94bff350fe0.png)
![image](https://user-images.githubusercontent.com/55490753/113872588-97346e00-97e6-11eb-9732-09ed7ba498d6.png)

**Comment by nicobonne** [comment]
Could you please remove the output of the previous print (line 81 and 82 in your code). It's hard to understand what's going on.

**Comment by zhuzhen1996** [comment]
![Uploading image.png…]()

**Comment by zhuzhen1996** [comment]
![image](https://user-images.githubusercontent.com/55490753/113873769-b089ea00-97e7-11eb-9882-a5cf9a27ccd2.png)
![image](https://user-images.githubusercontent.com/55490753/113873811-bbdd1580-97e7-11eb-9704-84f81cf5ccf1.png)

**Comment by nicobonne** [comment]
My bad, I obviously meant to remove line 80 and 81 instead of 81 and 82. Leave only `df_videos[df_videos.frames > 0].groupby('folder').apply(len)`

**Comment by zhuzhen1996** [comment]
I tried to reduce the data set and run it with twenty small data sets.

**Comment by zhuzhen1996** [comment]
不好意思，程序已经跑起来了。刚刚82的输出是：81行得到的输出数组打乱了顺序。不懂您明白我的意思嘛

**Comment by zhuzhen1996** [comment]
Sorry, the program is already running. The output of 82 just now is: the output array obtained at line 81 is out of order. Don't you understand what i mean

**Comment by nicobonne** [comment]
Sorry, I don't understand what you are asking. 
Stop everything is running, put a breakpoint on [this line](https://github.com/polimi-ispl/icpr2020dfdc/blob/f7039ecf3b62369db97b11dc7071e1091e042aa2/extract_faces.py#L81), open the Pycharm console and evaluate:
```python 
df_videos[df_videos.frames > 0].groupby('folder').apply(len)
```
then copy-paste here the output of the console instead of doing a screenshot. 
Thank you.

**Comment by zhuzhen1996** [comment]
Because your program uses arguments to pass parameters, it cannot run without passing parameters. I just deleted the parameters filled in, and my computer’s graphics card is 2060. Maybe the running program is not fast. I will see if the running result is complete tomorrow. Maybe it was my problem before. Please wait a moment, sorry!

**Comment by zhuzhen1996** [comment]
My program has just finished running, and there is no problem with your program. Except that the downloaded ninth data set has some problems after decompression, there are other results.
![image](https://user-images.githubusercontent.com/55490753/113980514-25593480-9879-11eb-9cb9-5936d80dcc4d.png)
![image](https://user-images.githubusercontent.com/55490753/113980526-2b4f1580-9879-11eb-9885-0b0169d1a9e3.png)

**Comment by zhuzhen1996** [comment]
Because my GPU is not very good, it may be slow to train. May I consider reducing the data set and use more than a dozen small data sets as training and testing data sets?

**Comment by nicobonne** [comment]
Glad to hear there are no problems. As I suggested [here](https://github.com/polimi-ispl/icpr2020dfdc/issues/27#issuecomment-810973424) you can modify the split function to have whatever split you want, just keep in mind results could worsen.

**Comment by zhuzhen1996** [comment]
Thank you very much for your patient guidance!
