### ISSUE TITLE
missing_keys after loading model in train_binclass.py

### ISSUE THREAD

**Issue by chinmaynehate** [polimi-ispl/icpr2020dfdc#37]
Hey,

_For FFPP dataset:_
EfficientNetB4 (Triplet)
I have kept the maxiter and valint arguments very small(just for testing)

- _I first ran train_triplet.py using:_
`python3 train_triplet.py --net EfficientNetB4 --traindb ff-c23-720-140-140 --valdb ff-c23-720-140-140 --ffpp_faces_df_path facesdf/faces_df.pkl --ffpp_faces_dir faces/ --face scale --size 224 --workers 0 --traintriplets 70 --valtriplets 20 --maxiter 2 --valint 1 --seed 0`

_Output:_
```
Loaded pretrained weights for efficientnet-b4
Parameters
{'face': 'scale',
 'net': 'EfficientNetB4',
 'seed': 0,
 'size': 224,
 'traindb': 'ff-c23-720-140-140'}
Tag: net-EfficientNetB4_traindb-ff-c23-720-140-140_face-scale_size-224_seed-0
Loading data
Training triplets: 70
Validation triplets: 20
Epoch 000: 2it [00:22, 11.59s/it] Maximum number of iterations reached
Completed        
```       
As expected, a bestval.pth file was saved in weights/triplet/net-EfficientNetB4_traindb-ff-c23-720-140-140_face-scale_size-224_seed-0/ directory

- _After this, I ran train_binclass.py using:_

`python3 train_binclass.py --net EfficientNetB4ST --traindb ff-c23-720-140-140 --valdb ff-c23-720-140-140 --ffpp_faces_df_path facesdf/faces_df.pkl --ffpp_faces_dir faces/ --face scale --size 224  --workers 0 --init weights/triplet/net-EfficientNetB4_traindb-ff-c23-720-140-140_face-scale_size-224_seed-0/bestval.pth --trainsamples 50 --valsamples 20 --maxiter 2  --valint 1 --seed 0
`
_Output:_
```
Loaded pretrained weights for efficientnet-b4
Parameters
{'face': 'scale',
 'net': 'EfficientNetB4ST',
 'seed': 0,
 'size': 224,
 'traindb': 'ff-c23-720-140-140'}
Tag: net-EfficientNetB4ST_traindb-ff-c23-720-140-140_face-scale_size-224_seed-0
Loading model form: weights/triplet/net-EfficientNetB4_traindb-ff-c23-720-140-140_face-scale_size-224_seed-0/bestval.pth
_IncompatibleKeys(missing_keys=['classifier.0.weight', 'classifier.0.bias', 'classifier.0.running_mean', 'classifier.0.running_var', 'classifier.1.weight', 'classifier.1.bias'], unexpected_keys=[])
Loading data
Training samples: 50
Validation samples: 20
Epoch 001: 0it [00:00, ?it/s]     Maximum number of iterations reached
Completed
```

- I am getting some incompatible keys at [line 187](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/train_binclass.py#L187)

Is this expected?
**OR**
"All keys matched successfully" should have been printed?

Thank you

**Comment by CrohnEngineer** [comment]
Hey @chinmaynehate ,

> Is this expected?
> OR
> "All keys matched successfully" should have been printed?

This is expected, as the final layers of the binary classifier and the triplet network are different.
Don't worry, your code is running fine :)
Thanks for passing by!
Bests,

Edoardo
