### ISSUE TITLE
Celeb Dataset training

### ISSUE THREAD

**Issue by zhuzhen1996** [polimi-ispl/icpr2020dfdc#48]
You have changed the two files train_binclass.py and split.py before. But notice that the two parameters related to celeb are not passed in the make_splits in split.py. I want to add training for the Celeb dataset in training.py. I would like to ask, do I need to modify other files if I add it directly to the parameter list? Can you edit and add it for me? There is another problem. It seems that you did not add the AUC accuracy parameter in train_triplet.py, and there is only the loss map in the obtained map.
![image](https://user-images.githubusercontent.com/55490753/117454935-3b8e0980-af79-11eb-813b-14373fba8332.png)
![image](https://user-images.githubusercontent.com/55490753/117455050-58c2d800-af79-11eb-85d8-0fad4874c9b0.png)

**Comment by CrohnEngineer** [comment]
Hey @zhuzhen1996 ,

> You have changed the two files train_binclass.py and split.py before. But notice that the two parameters related to celeb are not passed in the make_splits in split.py. I want to add training for the Celeb dataset in training.py

you're right. 
We are still not 100% sure about including the complete training pipeline for Celeb-DF as we didn't use this dataset in the original paper, and this is a repository primarily meant to replicate the results of a scientific paper. I hope you can understand.
Anyway, I think we can discuss this internally and choose if it is the case to go full way with the support of Celeb-DF: in that case, I will warn you when the code is ready for pulling from the master.
If you can't wait, the only modifications you need to do are in the [make_splits.py](https://github.com/polimi-ispl/icpr2020dfdc/blob/7f6059f35cc60794e031d285dc07a2938c9663bb/isplutils/split.py#L109) and [load_df.py](https://github.com/polimi-ispl/icpr2020dfdc/blob/7f6059f35cc60794e031d285dc07a2938c9663bb/isplutils/split.py#L28) functions, adding the parameters for the Celeb-DF faces DataFrame and faces directories paths. It should be really easy to modify this functions (you just need to copy the code used for FF and DFDC).

>  It seems that you did not add the AUC accuracy parameter in train_triplet.py, and there is only the loss map in the obtained map.

That's right! We only map the loss as this is the primarily metric we use in all the paper.
Again, if you want to add this I think it would be trivial. 
You are also welcome to open a PR for adding it as a functionality in the official repo :)
Bests,

Edoardo

**Comment by zhuzhen1996** [comment]
I know!Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Edoardo Daniele ***@***.***&gt;; 
发送时间: 2021年5月7日(星期五) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polimi-ispl/icpr2020dfdc] Celeb Dataset training (#48)





 
Hey @zhuzhen1996 ,
  
You have changed the two files train_binclass.py and split.py before. But notice that the two parameters related to celeb are not passed in the make_splits in split.py. I want to add training for the Celeb dataset in training.py
  
you're right.
 We are still not 100% sure about including the complete training pipeline for Celeb-DF as we didn't use this dataset in the original paper, and this is a repository primarily meant to replicate the results of a scientific paper. I hope you can understand.
 Anyway, I think we can discuss this internally and choose if it is the case to go full way with the support of Celeb-DF: in that case, I will warn you when the code is ready for pulling from the master.
 If you can't wait, the only modifications you need to do are in the make_splits.py and load_df.py functions, adding the parameters for the Celeb-DF faces DataFrame and faces directories paths. It should be really easy to modify this functions (you just need to copy the code used for FF and DFDC).
  
It seems that you did not add the AUC accuracy parameter in train_triplet.py, and there is only the loss map in the obtained map.
  
That's right! We only map the loss as this is the primarily metric we use in all the paper.
 Again, if you want to add this I think it would be trivial.
 You are also welcome to open a PR for adding it as a functionality in the official repo :)
 Bests,
 
Edoardo
