### ISSUE TITLE
"No validation samples" error when trying to train EfficientNetB4 on DFDC  

### ISSUE THREAD

**Issue by lmwijesundara** [polimi-ispl/icpr2020dfdc#49]
Hi,
Thanks for your great work. Your approach seems really interesting. When I was trying to train EfficientNetB4 model on DFDC sample data set I got this error.
![image](https://user-images.githubusercontent.com/19499866/119225307-a108fb00-bb20-11eb-9b20-22cb60ad9eae.png)

here is my script
![image](https://user-images.githubusercontent.com/19499866/119225412-5045d200-bb21-11eb-9a4b-76e5fdc33755.png)

Thanks in advance!

**Comment by CrohnEngineer** [comment]
Hey @lmwijesundara ,

thanks for passing by!
One question: have you extracted the faces from all the 50 folders of DFDC?
We use for training the faces from the first 35 folders, for validation from the folders from 35 to 40, and from the last 10 for testing.
If you didn't extract faces from the folders from 35 to 40, the scripts likely didn't found any validation samples and therefore stopped.
Let us know!
Bests,

Edoardo

**Comment by lmwijesundara** [comment]
I used DFDC sample dataset provided by the Kaggle site.

**Comment by nicobonne** [comment]
You need to use the full dataset to replicate our results, since we base our split on the folders of the full dataset. The sample dataset is not enough
