### ISSUE TITLE
How to solve the problem of overfitting in training ?

### ISSUE THREAD

**Issue by miaoct** [polimi-ispl/icpr2020dfdc#5]
or how to select the best model as the final submission model ?

 I also participated in DFDC, but only got 94 places .
 
Thank you !

**Comment by nicobonne** [comment]
Well, that's a million dollar question 😉

Overfitting was a big problem in DFDC, and the fact that the training dataset was composed by a few actors surely didn't help.
Adding external data to the training set would have helped but we decided to keep only the original dataset to avoid the risk of being disqualified. 

A way to reduce overfitting for the challenge was to split the original dataset into non overlapping subset and train several instances of the same model over those separated sets. You can find a little more in our[ Kaggle post](https://www.kaggle.com/c/deepfake-detection-challenge/discussion/145841).
