### ISSUE TITLE
FaceForensics++DataSet

### ISSUE THREAD

**Issue by zhuzhen1996** [polimi-ispl/icpr2020dfdc#54]
Sorry to trouble you again! I would like to ask about the FF++ data set space you are using. I downloaded it once before. The catalog looks like this, but it seems that the program index_ffpp.py cannot be used. I have always used the DFDC data set before. Now I re-use the download script to download the compressed data set of 130G, is it the same as the data set you used in the code?
This is the structure of the data set I downloaded before, about 100G like this
![image](https://user-images.githubusercontent.com/55490753/123054924-ef6b2b80-d437-11eb-89e8-ba56a030a29b.png)
![image](https://user-images.githubusercontent.com/55490753/123055024-0a3da000-d438-11eb-9c78-0c184a627f8a.png)

This is a screenshot of the procedure I got by filling out the form
![image](https://user-images.githubusercontent.com/55490753/123055207-3822e480-d438-11eb-8313-7271abc048a0.png)
![image](https://user-images.githubusercontent.com/55490753/123055364-60124800-d438-11eb-9d1c-049c2633eff7.png)

**Comment by nicobonne** [comment]
I confirm you need the compressed version, we didn't use the raw videos in the paper.

**Comment by zhuzhen1996** [comment]
Do you also use the compressed version in your code? The raw version of the data set is too big, and the hard disk storage space of the computer is really not enough.

**Comment by nicobonne** [comment]
You don't need the raw version, you only need the compressed version. More specifically, you only need the `c23` compression quality factor, you can discard everything else.

**Comment by zhuzhen1996** [comment]
Thank You!
