### ISSUE TITLE
What is the Training set of those pre-trianed models that provided by your dropbox link

### ISSUE THREAD

**Issue by Chancing0** [polimi-ispl/icpr2020dfdc#55]
Hello,
As the title, I just want to know what are the training sets of the DFDC and FFPP models?
I mean for the training set, we have HQ (23% compression) and LQ and raw data. 
I got your pre-trained model without the description of the training set.

**Comment by CrohnEngineer** [comment]
Hey @Chancing0 ,

for the DFDC, we relied on the raw data and did not use the HQ nor the LQ data.
We proceeded in this way for two reasons:
1. we extracted the faces from each video and saved them as JPEG (even though with a high quality factor, 95);
2. during training, as data-augmentation we perform JPEG compression with ranging quality factor to simulate a video compression operation (even though surely video compression is a more hard operation on data quality).

For the FF++, we used instead original video and c23 compressed videos.
Hope this helps!
Bests,

Edoardo
