### ISSUE TITLE
Analyze results

### ISSUE THREAD

**Issue by zhuzhen1996** [polimi-ispl/icpr2020dfdc#56]
Hello, I install step training data. But when I opened the jupyter notebook and ran Analyze results, the following error appeared.
![image](https://user-images.githubusercontent.com/55490753/124880105-815e6100-e000-11eb-9208-bee19be1031d.png)
My result folder structure is as follows
![image](https://user-images.githubusercontent.com/55490753/124880229-a357e380-e000-11eb-98e8-23bddfd490e7.png)
![Uploading image.png…]()
Look at the code, it seems that the .csv file is created automatically, I am very confused

**Comment by zhuzhen1996** [comment]
![image](https://user-images.githubusercontent.com/55490753/124880915-5de7e600-e001-11eb-9e60-0ed66a71a36e.png)

**Comment by zhuzhen1996** [comment]
![image](https://user-images.githubusercontent.com/55490753/124881150-9c7da080-e001-11eb-92a6-9024be498c22.png)

**Comment by CrohnEngineer** [comment]
Hey @zhuzhen1996 ,

looking at the first image you have a `FileNotFoundError: [Errno2] No such file or directory 'results\\frames.csv' `.
Are you running the notebook inside the `notebook` folder?
If that is the case, then you need to set the value of the `results_root`  variable in cell 3 to `results_root='..\results'`, as probably the code is searching for a `results` folder inside the `notebook` folder without finding one.
Let me know!
Bests,

Edoardo

**Comment by zhuzhen1996** [comment]
Thank you!II have solved this problem！

**Comment by CrohnEngineer** [comment]
Glad to hear that :)
Bests,

Edoardo
