### ISSUE TITLE
Celebdf dataset

### ISSUE THREAD

**Issue by WajidaAnwar** [polimi-ispl/icpr2020dfdc#60]
--traindb ff-c23-720-140-140 \
--valdb ff-c23-720-140-140 \
I am facing difficulties in understanding the significance of these in train_all.sh
If I want to train the celebdf dataset what should I replace these with?

**Comment by CrohnEngineer** [comment]
Hey @WajidaAnwar ,

> --traindb ff-c23-720-140-140
> --valdb ff-c23-720-140-140
> I am facing difficulties in understanding the significance of these in train_all.sh

these all the splits used for the FaceForensics++ dataset.

> If I want to train the celebdf dataset what should I replace these with?

We do not provide full support for training the models on CelebDF, as this repository is meant for reproducing the results of the paper we presented at ICPR2020, and we didn't use CelebDF in our experiments.
If you want to train on CelebDF, refer to these issues #38 #48 where we provided other information on how to proceed.
Bests,

Edoardo
