### ISSUE TITLE
Can't find the file data_frame_df.pkl

### ISSUE THREAD

**Issue by yuan-yuan321** [polimi-ispl/icpr2020dfdc#61]
![image](https://user-images.githubusercontent.com/46087050/129323695-fd113a90-cb25-4996-acaa-27b7598098f2.png)

**Comment by CrohnEngineer** [comment]
Hey @yuan-yuan321 ,

Please provide a more detailed description of your error, for instance: have you followed all the steps indicated in the README.md for running our experiments?
Bests,

Edoardo

**Comment by yuan-yuan321** [comment]
![image](https://user-images.githubusercontent.com/46087050/129337003-b2aca566-30ef-4fb9-a418-f22e857c9457.png)

**Comment by CrohnEngineer** [comment]
I understood that you're missing the Dataframe containing the test results.
What I'm asking you is: why are you missing it?
Did you check if the path is correct?
Have you followed the instructions in the README.md to pre-process the dataset, train the models, and then test them?
I can't help you seeing only these screenshots.
