### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by jessiZO** [polimi-ispl/icpr2020dfdc#63]
Hey. I have a question.
Have you used all the frames extracted from each video to identify a real/fake video? I tried looking for it but since I'm a starter I am facing difficulties in understanding the code.
One more thing, you have used the scores obtained from each frame to classify the whole 
video right?

**Comment by CrohnEngineer** [comment]
Hey @jessiZO ,

for information regarding the experimental setup you can refer to the [paper](https://ieeexplore.ieee.org/document/9412711) we have presented at ICPR2020.
Answering your questions: we used 32 frames per video both in training and in testing, so to classify a whole video we consider the scores extracted from 32 frames selected equally spaced in time.
Bests,

Edoardo

**Comment by jessiZO** [comment]
So you took average of the scores obtained from those 32 frames?

**Comment by CrohnEngineer** [comment]
Yes, we took the average of the pre-sigmoid scores and then we computed the sigmoid on the mean score of the whole video :)

**Comment by jessiZO** [comment]
The split procedure that you followed for celeb df dataset, will it handle
the imbalance in the dataset?
