### ISSUE TITLE
Unable to find "List_of_testing_videos.txt" 

### ISSUE THREAD

**Issue by yumiaomiao111116** [polimi-ispl/icpr2020dfdc#64]
hello, when i run the python index_celebdf.py,  the error is FileNotFoundError: Unable to find "List_of_testing_videos.txt" in datasets/celeb-DF. I wanna know what is the 'List_of_testing_videos.txt' file? and how can i get it? thank you so much

**Comment by nicobonne** [comment]
Hi @yumiaomiao111116, as already mentioned in [this closed issue](https://github.com/polimi-ispl/icpr2020dfdc/issues/38#issuecomment-821858261), that list should be included in the dataset. Try re-downloading it.
