### ISSUE TITLE
extractfaces.py --videodf argument

### ISSUE THREAD

**Issue by HiraJamshed20** [polimi-ispl/icpr2020dfdc#7]
What is the video dataframe that seems to be required here? Not passing anything returns None which makes it problematic for the script to run

**Comment by nicobonne** [comment]
Hi @HiraJamshed20,
you should pass the path to the previously computed dataframe starting from the source directory.
In scripts/make_dataset.sh you can find an example of the required steps.

But you're right, `--videodf` argument should be required. I'm fixing this in the next commit.

Thanks for pointing out 💯
