### ISSUE TITLE
how to set validation split for dfdc?

### ISSUE THREAD

**Issue by zeemezeeme** [polimi-ispl/icpr2020dfdc#70]
i am having following issue in train_binclass.py for dfdc
Training samples: 384
Validation samples: 0 

seems like i dont have validation split ready , can someone help me in order to fix this issue.

**Comment by zeemezeeme** [comment]
ok i found out that dfdc-35-5-10 are division of data according to folders. so basically i have to download all 470 GB of data in order to run the code, is there any way i can run this for small dataset ?

**Comment by nicobonne** [comment]
You can easily modify the [splitting code](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/isplutils/split.py) to suit your needs, like defining less folders for training and validation.

**Comment by zeemezeeme** [comment]
thank you for your swift reply , i have tried it . 
i changed this part according to my needs
--------------------------------------------------------------
  if split == 'train':
            split_df = df[df['folder'].isin(range(35))]
        elif split == 'val':
            split_df = df[df['folder'].isin(range(35, 40))]
        elif split == 'test':
            split_df = df[df['folder'].isin(range(40, 50))]
--------------------------------------------------------
but still having this error while working on colab:

![image](https://github.com/polimi-ispl/icpr2020dfdc/assets/96488900/9ce58b40-34b7-41a2-994b-52c1d131e110)

**Comment by nicobonne** [comment]
You are probably trying to sample from an empty list, due to some path mismatch. Check your paths.
