### ISSUE TITLE
regarding attention heatmap

### ISSUE THREAD

**Issue by tapas** [polimi-ispl/icpr2020dfdc#72]
Thanks for the good work, just a query, the model provides attention map for both fake and real content. in this case how can we differentiate. How can we improve attention mechanism to get more clear heat maps ? Thanks

**Comment by CrohnEngineer** [comment]
Hi @tapas ,

Thank you for checking our work out!
Regarding the "heatmap", please be aware that it is not a heatmap but an **Attention** map.
The attention map does not provide hints about the "fakeness" or "genuineness" of the frame but instead tells us which visual details (e.g., the nose, the ears, the forehead, etc.) the network is focusing on. This is done regardless of whether the frame is real or fake.
The production of heatmaps for telling apart fake from real content is still an open research topic, mainly related to the explainable AI (xAI) field.
You can find many works in the literature, but you can refer to [this](https://arxiv.org/abs/2105.05902) as a starting point.
I hope this helps!
Bests,

Edoardo
