### ISSUE TITLE
EnvironmentNameNotFound: Could not find conda environment: icpr2020

### ISSUE THREAD

**Issue by y2jcodebreaker** [polimi-ispl/icpr2020dfdc#75]
I got this error while activating the icpr2020 environment. Following is the attached screenshot of the problem.
![icpr2020](https://github.com/polimi-ispl/icpr2020dfdc/assets/144542033/54d5c666-5a44-455b-ba22-8d27141da652)

**Comment by CrohnEngineer** [comment]
Hey @y2jcodebreaker ,

Thanks for checking out our repo!  
Before activating the `icpr2020` environment, you must create it using the `environment.yml` file.  
All the instructions are listed in the [README.md](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/README.md) file, but in short, you have to run:
```bash
$ conda env create -f environment.yml
$ conda activate icpr2020
```

Have fun!

**Comment by y2jcodebreaker** [comment]
I ran the code and created the environment yet I am still facing the same issue.

**Comment by CrohnEngineer** [comment]
From the pic you posted, i.e., the result of the conda info --envs command, you have only the base environment installed.  
So either the installation wasn't successful, or you did not install the environment at all, or, if you have multiple conda installation, you have installed the icpr2020 environment in another conda setup.  
Please try installing the environment again using the yaml file, thanks!
