### ISSUE TITLE
val_sample

### ISSUE THREAD

**Issue by allprover** [polimi-ispl/icpr2020dfdc#77]
![8`91U}0SOC6OTG1_S$(12~W](https://github.com/polimi-ispl/icpr2020dfdc/assets/97093549/edb4d68e-a9b1-4ad3-9922-1fd687cddbbd)
Please help me see why

**Comment by CrohnEngineer** [comment]
Hi @allprover, I guess you found the solution by yourself! Let us know if you encounter any other problems.
