### ISSUE TITLE
Build a heatmap

### ISSUE THREAD

**Issue by HiraJamshed20** [polimi-ispl/icpr2020dfdc#9]
Hello!

I want to convert the images that show the attention masks into a heatmap on the images. Would you be able to guide me as to how I could do that?

**Comment by bestagini** [comment]
Hi, [this notebook](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/notebook/Image%20prediction%20and%20attention.ipynb) shows how to compute the attention mask and how to overlay it on the face image.

**Comment by HiraJamshed20** [comment]
Hello! Yes, this shows it in a picture form, in the form of pixels. I was looking for converting it to heatmaps similar to these https://glassboxmedicine.com/2019/06/11/cnn-heat-maps-class-activation-mapping-cam/

**Comment by bestagini** [comment]
Considering [the notebook mentioned above](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/notebook/Image%20prediction%20and%20attention.ipynb), have a look at cell number 15. You can get the face image from variable `face_im` and the heatmap from variable `att_img `. A simple way of superimposing the heatmap to the image can then be found [here](https://github.com/durandtibo/heatmap).
